#!/usr/bin/env python3
"""Stamp a house-shaped Obsidian .base file for one entity collection.

Usage:
  new-base.py <entity>            entity: person | company | document
  new-base.py --list              show the registry
  new-base.py <entity> --root X   operate on another scaffold root

Per GL-006: Bases are VIEWS over frontmatter and are generated, never
hand-authored. Guards (code, not prose):
  - refuses an entity type that is not in the registry
  - refuses to overwrite an existing .base
  - refuses a registry column that GL-002 does not declare (a drifted
    registry must lose to the guideline, never win)
  - refuses when the target folder does not exist
"""
import argparse, re, sys
from pathlib import Path

DEFAULT_ROOT = Path(__file__).resolve().parents[3]
GL002 = "06 AI Team/AI Team Knowledge/Guidelines/GL-002-frontmatter-conventions.md"

# The registry: which collections earn a Base, and their canonical
# table shape. Columns are GL-002 note properties; file.name is always
# the identity column and is added by render(), not listed here.
REGISTRY = {
    "person": {
        "folder": "04 Inner World/Contacts/People",
        "base": "People.base",
        "view": "People",
        "type_value": "person",
        "columns": [
            ("role", "Role"),
            ("relation", "Relation"),
            ("companies", "Companies"),
            ("email", "Email"),
            ("last_contact", "Last contact"),
            ("next_action", "Next action"),
        ],
        "sort": ("file.name", "ASC"),
        "cards_image": None,
    },
    "company": {
        "folder": "04 Inner World/Contacts/Companies",
        "base": "Companies.base",
        "view": "Companies",
        "type_value": "company",
        "columns": [
            ("industry", "Industry"),
            ("people", "People"),
            ("website", "Website"),
        ],
        "sort": ("file.name", "ASC"),
        "cards_image": None,
    },
    "document": {
        "folder": "04 Inner World/Documents",
        "base": "Documents.base",
        "view": "Documents",
        "type_value": "document",
        "columns": [
            ("doc_type", "Kind"),
            ("issued_on", "Issued"),
            ("expiry_date", "Expires"),
            ("amount", "Amount"),
            ("currency", "Currency"),
            ("source_file", "File"),
        ],
        "sort": ("note.issued_on", "DESC"),
        "cards_image": "note.preview_image",
    },
}

# Fields every note carries per GL-002's common block.
COMMON_FIELDS = {"type", "created", "tags"}


def gl002_fields(root):
    """Parse GL-002's per-type table into {type: set(fields)}.
    Deterministic: reads the markdown table, strips parentheticals
    (they hold enums and commentary, and may contain commas)."""
    text = (root / GL002).read_text(encoding="utf-8")
    out = {}
    for line in text.splitlines():
        m = re.match(r"^\|\s*([a-z-]+(?:\s*/\s*[a-z-]+)*)\s*\|(.+)\|(.+)\|\s*$", line)
        if not m:
            continue
        tname = m.group(1)
        if tname in ("type", "---", "--- "):
            continue
        fields = set()
        for cell in (m.group(2), m.group(3)):
            cell = re.sub(r"\([^)]*\)", "", cell)
            for f in cell.split(","):
                f = f.strip()
                if re.fullmatch(r"[a-z][a-z0-9_]*", f):
                    fields.add(f)
        for t in re.split(r"\s*/\s*", tname):
            out[t] = fields | COMMON_FIELDS
    return out


def render(entity):
    e = REGISTRY[entity]
    L = []
    L.append("# Generated by 06 AI Team/AI Team Knowledge/Scripts/new-base.py")
    L.append("# Columns are GL-002 fields. To change them: update GL-002,")
    L.append("# then the registry in new-base.py, then re-stamp (GL-006).")
    L.append("filters:")
    L.append("  and:")
    L.append('    - file.inFolder("%s")' % e["folder"])
    L.append('    - file.ext == "md"')
    L.append('    - note.type == "%s"' % e["type_value"])
    L.append("properties:")
    L.append("  file.name:")
    L.append("    displayName: Name")
    for prop, disp in e["columns"]:
        L.append("  note.%s:" % prop)
        L.append("    displayName: %s" % disp)
    L.append("views:")
    L.append("  - type: table")
    L.append("    name: %s" % e["view"])
    L.append("    order:")
    L.append("      - file.name")
    for prop, _ in e["columns"]:
        L.append("      - note.%s" % prop)
    L.append("    sort:")
    L.append("      - property: %s" % e["sort"][0])
    L.append("        direction: %s" % e["sort"][1])
    if e["cards_image"]:
        L.append("  - type: cards")
        L.append("    name: %s gallery" % e["view"])
        L.append("    image: %s" % e["cards_image"])
        L.append("    order:")
        L.append("      - file.name")
        for prop, _ in e["columns"][:3]:
            L.append("      - note.%s" % prop)
    return "\n".join(L) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("entity", nargs="?")
    ap.add_argument("--list", action="store_true")
    ap.add_argument("--root", default=None)
    a = ap.parse_args()
    root = Path(a.root).resolve() if a.root else DEFAULT_ROOT

    if a.list:
        for name, e in REGISTRY.items():
            print("%-10s -> %s/%s" % (name, e["folder"], e["base"]))
        return 0

    if not a.entity:
        sys.exit("FAIL name an entity type (or --list)")
    if a.entity not in REGISTRY:
        sys.exit("FAIL unknown entity type %r; registry knows: %s"
                 % (a.entity, ", ".join(sorted(REGISTRY))))

    e = REGISTRY[a.entity]
    declared = gl002_fields(root).get(e["type_value"], COMMON_FIELDS)
    undeclared = [p for p, _ in e["columns"] if p not in declared]
    if undeclared:
        sys.exit("FAIL registry columns not declared in GL-002 for %r: %s "
                 "(update the guideline first, per CLAUDE.md hard rule 4)"
                 % (a.entity, ", ".join(undeclared)))

    folder = root / e["folder"]
    if not folder.is_dir():
        sys.exit("FAIL target folder missing: %s" % e["folder"])
    dest = folder / e["base"]
    if dest.exists():
        sys.exit("FAIL %s exists, refusing to overwrite "
                 "(delete it first if a re-stamp is intended)"
                 % dest.relative_to(root))

    dest.write_text(render(a.entity), encoding="utf-8")
    print("OK stamped -> %s" % dest.relative_to(root))
    return 0


if __name__ == "__main__":
    sys.exit(main())
